import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { getChapters } from "@/lib/chapters";
import { cn } from "@/lib/utils";

/* Inter is the existing app face; expose it as --font-sans for ShadCN tokens. */
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Vs PsychDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /* Catalog is read once on the server and passed into the client nav. */
  const chapters = getChapters();

  return (
    /* suppressHydrationWarning: next-themes may add `.dark` before React hydrates. */
    <html
      id="main_doc"
      lang="en"
      className={cn("font-sans", inter.variable)}
      suppressHydrationWarning
    >
      {/* Page pattern is on body in globals.css; routes do not paint a background. */}
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Navbar chapters={chapters} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
