import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getChapters } from "@/lib/chapters";
import { cn } from "@/lib/utils";

/* Inter is the existing app face; expose it as --font-sans for ShadCN tokens. */
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Vs PsychDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /* Catalog is read once on the server and passed into the client nav. */
  const chapters = getChapters();

  return (
    /* `.dark` selects neobrutalist dark tokens (class-based, not prefers-color-scheme). */
    <html
      id="main_doc"
      lang="en"
      className={cn("dark font-sans", inter.variable)}
    >
      {/* Page pattern is on body in globals.css; routes do not paint a background. */}
      <body className="antialiased">
        <Navbar chapters={chapters} />
        {children}
      </body>
    </html>
  );
}
